{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pcap-analyzer.fullname" . }}
  labels:
    {{- include "pcap-analyzer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.external.enabled }}
  # External PostgreSQL (user-provided URL)
  DATABASE_URL: {{ .Values.postgresql.external.url | quote }}
  {{- else }}
  # Internal PostgreSQL (official postgres:16-alpine StatefulSet)
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "pcap-analyzer.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  {{- end }}
  SECRET_KEY: {{ .Values.secretKey | default (randAlphaNum 64) | quote }}
{{- end }}
